version: "3.6"
services:
  db:
    build: docker-db/
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD
      - POSTGRES_DB=otohime
      - POSTGRES_DB_USER=otohime
      - POSTGRES_DB_PASSWORD
    volumes:
      - dbdata:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "127.0.0.1:8580:8080"
    depends_on:
      - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://otohime:${POSTGRES_DB_PASSWORD}@db:5432/otohime
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_AUTH_HOOK: http://hooks:8787/auth/
  hooks:
    build: hooks/
    depends_on:
      - "db"
      - "hasura"
    environment:
      FIREBASE_ID: ${FIREBASE_ID}
      PGUSER: otohime
      PGDATABASE: otohime
      PGHOST: db
      PGPASSWORD: ${POSTGRES_DB_PASSWORD}
volumes:
  dbdata:
